### ISSUE TITLE
ERROR:assign-cgroups:Failed to modify cgroup for Standard Notes

### ISSUE THREAD

**Issue by rhubinak** [alebastr/sway-systemd#14]
Hey,

Stumbled upon this error while booting up the system and running [Standard Notes](https://standardnotes.com/) on sway session exec (autostart):

```
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]: ERROR:assign-cgroups:Failed to modify cgroup for Standard Notes
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]: Traceback (most recent call last):
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:   File "/usr/libexec/sway-systemd/assign-cgroups.py", line 243, in _on_new_window
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:     await self.assign_scope(app_id, proc)
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:   File "/usr/lib/python3.10/site-packages/tenacity/_asyncio.py", line 86, in async_wrapped
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:     return await fn(*args, **kwargs)
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:   File "/usr/lib/python3.10/site-packages/tenacity/_asyncio.py", line 48, in __call__
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:     do = self.iter(retry_state=retry_state)
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:   File "/usr/lib/python3.10/site-packages/tenacity/__init__.py", line 360, in iter
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:     raise retry_exc.reraise()
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:   File "/usr/lib/python3.10/site-packages/tenacity/__init__.py", line 193, in reraise
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:     raise self.last_attempt.result()
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:   File "/usr/lib64/python3.10/concurrent/futures/_base.py", line 438, in result
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:     return self.__get_result()
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:   File "/usr/lib64/python3.10/concurrent/futures/_base.py", line 390, in __get_result
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:     raise self._exception
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:   File "/usr/lib/python3.10/site-packages/tenacity/_asyncio.py", line 51, in __call__
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:     result = await fn(*args, **kwargs)
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:   File "/usr/libexec/sway-systemd/assign-cgroups.py", line 217, in assign_scope
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:     await self._sd_manager.call_start_transient_unit(
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:   File "/usr/lib/python3.10/site-packages/dbus_next/aio/proxy_object.py", line 92, in method_fn
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:     BaseProxyInterface._check_method_return(msg, intr_method.out_signature)
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:   File "/usr/lib/python3.10/site-packages/dbus_next/proxy_object.py", line 62, in _check_method_return
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]:     raise DBusError._from_message(msg)
Jan 18 17:21:55 laptop /usr/libexec/gdm-wayland-session[2593]: dbus_next.errors.DBusError: Invalid unit name or type.
```

No issue with Standard Notes observed. It started successfully, so this is probably harmless. Could be related to https://github.com/alebastr/sway-systemd/issues/8

Environment:
Fedora 35
sway-1.6.1-3.fc35.x86_64
sway-systemd-0.2.1-1.fc35.noarch
standard-notes-3.9.13-linux-x86_64.AppImage
[sway config](https://github.com/rhubinak/dotfiles/blob/master/.config/sway/config)

**Comment by alebastr** [comment]
> dbus_next.errors.DBusError: Invalid unit name or type.

I suspect there's something interesting and unexpected in the `WM_CLASS` property of the window. Whitespaces, punctuation marks or anything else I forgot to escape in the script.

Can you please get the object with Standard Notes window from `swaymsg -t get_tree` output?

**Comment by rhubinak** [comment]
Sure, here you go:

```
        {
          "id": 23,
          "type": "workspace",
          "orientation": "vertical",
          "percent": null,
          "urgent": false,
          "marks": [
          ],
          "focused": false,
          "layout": "splitv",
          "border": "none",
          "current_border_width": 0,
          "rect": {
            "x": 2560,
            "y": 30,
            "width": 1200,
            "height": 1890
          },
          "deco_rect": {
            "x": 0,
            "y": 0,
            "width": 0,
            "height": 0
          },
          "window_rect": {
            "x": 0,
            "y": 0,
            "width": 0,
            "height": 0
          },
          "geometry": {
            "x": 0,
            "y": 0,
            "width": 0,
            "height": 0
          },
          "name": "4",
          "window": null,
          "nodes": [
            {
              "id": 24,
              "type": "con",
              "orientation": "none",
              "percent": 1.0,
              "urgent": false,
              "marks": [
              ],
              "focused": false,
              "layout": "tabbed",
              "border": "none",
              "current_border_width": 0,
              "rect": {
                "x": 2560,
                "y": 30,
                "width": 1200,
                "height": 1890
              },
              "deco_rect": {
                "x": 0,
                "y": 0,
                "width": 0,
                "height": 0
              },
              "window_rect": {
                "x": 0,
                "y": 0,
                "width": 0,
                "height": 0
              },
              "geometry": {
                "x": 0,
                "y": 0,
                "width": 0,
                "height": 0
              },
              "name": null,
              "window": null,
              "nodes": [
                {
                  "id": 22,
                  "type": "con",
                  "orientation": "none",
                  "percent": 1.0,
                  "urgent": false,
                  "marks": [
                  ],
                  "focused": false,
                  "layout": "none",
                  "border": "none",
                  "current_border_width": 2,
                  "rect": {
                    "x": 2560,
                    "y": 55,
                    "width": 1200,
                    "height": 1865
                  },
                  "deco_rect": {
                    "x": 0,
                    "y": 0,
                    "width": 1200,
                    "height": 25
                  },
                  "window_rect": {
                    "x": 0,
                    "y": 0,
                    "width": 1200,
                    "height": 1865
                  },
                  "geometry": {
                    "x": 0,
                    "y": 0,
                    "width": 1200,
                    "height": 1865
                  },
                  "name": "Standard Notes",
                  "window": 4194307,
                  "nodes": [
                  ],
                  "floating_nodes": [
                  ],
                  "focus": [
                  ],
                  "fullscreen_mode": 0,
                  "sticky": false,
                  "pid": 2580,
                  "app_id": null,
                  "visible": false,
                  "max_render_time": 0,
                  "shell": "xwayland",
                  "inhibit_idle": false,
                  "idle_inhibitors": {
                    "user": "none",
                    "application": "none"
                  },
                  "window_properties": {
                    "class": "Standard Notes",
                    "instance": "standard notes",
                    "title": "Standard Notes",
                    "transient_for": null,
                    "window_role": "browser-window",
                    "window_type": "normal"
                  }
                }
              ],
              "floating_nodes": [
              ],
              "focus": [
                22
              ],
              "fullscreen_mode": 0,
              "sticky": false
            }
          ],
          "floating_nodes": [
          ],
          "focus": [
            24
          ],
          "fullscreen_mode": 1,
          "sticky": false,
          "num": 4,
          "output": "DP-2",
          "representation": "V[T[Standard Notes]]"
        },
```

**Comment by alebastr** [comment]
Thanks!

`"class": "Standard Notes",` - I forgot that WM_CLASS has much looser validation compared to the wayland app_id. It's basically any null-terminated ASCII or Latin-1 string without control characters.

I'll have to add a proper escaping in the next release.
