### ISSUE TITLE
ERROR:assign-cgroups:Failed to modify cgroup for None

### ISSUE THREAD

**Issue by ibrokemypie** [alebastr/sway-systemd#8]
Not really sure how I caused this issue, it occurred after starting spotify with rofi. assign-cgroups.py crashed with the following output:
```
ERROR:assign-cgroups:Failed to modify cgroup for None
Traceback (most recent call last):
  File "/usr/lib/sway-systemd/assign-cgroups.py", line 219, in _on_new_window
    await self.assign_scope(app_id, pid)
  File "/usr/lib/python3.9/site-packages/tenacity/_asyncio.py", line 75, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tenacity/_asyncio.py", line 38, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 367, in iter
    return fut.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/site-packages/tenacity/_asyncio.py", line 41, in __call__
    result = await fn(*args, **kwargs)
  File "/usr/lib/sway-systemd/assign-cgroups.py", line 186, in assign_scope
    app_id = escape_app_id(app_id)
  File "/usr/lib/sway-systemd/assign-cgroups.py", line 66, in escape_app_id
    return app_id.replace("-", "\\x2d")
AttributeError: 'NoneType' object has no attribute 'replace'
```

--- edit
Didn't crash, I was wrong, so this issue is probably harmless and can be closed (I think?)

**Comment by alebastr** [comment]
Thanks for reporting!

This actually uncovered a problem I forgot to to take into account: X11 applications are not required to set WM_CLASS. Spotify and Steam are two main examples that used to do that.
Spotify window lacks any kind of meaningful id, so the script failed to generate a name for a new cgroup and left spotify process in the same group as the compositor.

Fixed in main as of https://github.com/alebastr/sway-systemd/commit/ac7f840b518ae5d5e831ba358fc8a2db32e4dcfb.
